version: '3'
services:
  nginx:
    image: nginx:1.17.8
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - net
  php:
    build:
      context: docker/php-fpm
    volumes:
      - ./code:/code
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      - net
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'base'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24